version: '3.9'
services:
  api:
    build:
      context: .
      target: build
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    depends_on:
      - database
    command: npm run dev
  database:
    image: mongo:5.0.6-focal
    ports:
      - 27017:27017
    volumes:
      - ./.data/db:/data/db:delegated
